blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/harveyzhang814/whisper-docker-api/discussions
    about: Please ask and answer questions here.
  - name: Security Issues
    url: https://github.com/harveyzhang814/whisper-docker-api/security/policy
    about: Please report security vulnerabilities here. 