version: '3.8'

services:
  whisper-server:
    build:
      context: ..
      dockerfile: docker_api/Dockerfile
    platform: linux/arm64
    ports:
      - "${API_PORT:-8090}:${API_PORT:-8090}"
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    env_file:
      - .env.docker.local
    environment:
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-8090}
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
      - BATCH_SIZE=${BATCH_SIZE:-16}
      - SAMPLE_RATE=${SAMPLE_RATE:-16000}
      - CHUNK_SIZE=${CHUNK_SIZE:-1024}
      - CHANNELS=${CHANNELS:-1}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    restart: unless-stopped 